### ISSUE TITLE
Multiple Dependencies Errors While using mavern

### ISSUE THREAD

**Issue by titus-shoats** [richkmeli/Richkware-Manager-Server#3]
Hello im trying to setup the framework server, but im getting an dependencies error while using mavern. I use the command "mvn package", Then I get the error below

 mvn package

[ERROR] Failed to execute goal on project Richkware-Manager-Server: Could not re
solve dependencies for project it.richkmeli.rms:Richkware-Manager-Server:war:1.1
.2: Failed to collect dependencies at it.richkmeli.jframework:auth-core:jar:1.2.
6: Failed to read artifact descriptor for it.richkmeli.jframework:auth-core:jar:
1.2.6: Could not transfer artifact it.richkmeli.jframework:auth-core:pom:1.2.6 f
rom/to github (https://maven.pkg.github.com/richkmeli/JFramework): Authenticatio
n failed for https://maven.pkg.github.com/richkmeli/JFramework/it/richkmeli/jfra
mework/auth-core/1.2.6/auth-core-1.2.6.pom 401 Unauthorized -> [Help 1]

**Comment by richkmeli** [comment]
Hello, the problem was the jFramework 1.2.6 was only present on GitHub repo, anyway I deployed even on Jitpack, now it should work.
Thanks.
